In [1]:
import pickle
import json

In [6]:
with open(r"D:\Thesis\rerun\wor2vec\fold_0\vocab_200.json",'r') as f:
    fi=json.load(f) 
newf=open('dict_200.pkl','wb')
pickle.dump(fi,newf)

In [12]:
from han.han import WordAttn
import torch

In [26]:
np.random.rand(3,3).astype(np.float64)

array([[0.36663485, 0.94865797, 0.15916494],
       [0.78627424, 0.87107214, 0.83101998],
       [0.4969982 , 0.08944458, 0.74877767]])

In [35]:
word=WordAttn(200,'cpu')

word(torch.rand(200,200))


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [10]:
import json 
import os
import numpy as np

In [11]:
path=r"D:\Thesis\rerun\wor2vec\fold_0\vocab_200.json"
with open(path,'r') as f:
    wdv=json.load(f)

In [31]:
#wdv.keys()

In [32]:
len(wdv['delhi'])

200

In [8]:
embed_size=200

In [10]:
embedding_matrix = np.zeros((len(word_index) + 1, embed_size))
absent_words = 0
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # words not found in embedding index will be all-zeros.
        embedding_matrix[i] = embedding_vector
    else:
        absent_words += 1
print('Total absent words are', absent_words, 'which is', "%0.2f" % (absent_words * 100 / len(word_index)), '% of total words')

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
"""
1.data prepartion 
2.model input
3.doc embedding 

"""

In [7]:
import torch.nn as nn
import torch.nn.functional as F
import torch


In [53]:
input_dim=3
x=torch.rand(3,3)
m=nn.Linear(in_features=input_dim,out_features=input_dim,bias=True)
out=m(x)

In [54]:
out=nn.Tanh()(out)

In [55]:
out

tensor([[ 0.2104, -0.5039, -0.3376],
        [-0.3498, -0.6957, -0.2947],
        [ 0.2009, -0.3575, -0.1813]], grad_fn=<TanhBackward0>)

In [56]:
param=nn.Parameter(torch.Tensor(input_dim,1))
weights=param.data.normal_(mean=0.0,std=0.05)

In [57]:
out =torch.matmul(out,param)
out=torch.squeeze(out,dim=-1)
att_w=F.softmax(out,dim=-1)


In [58]:
out

tensor([0.0121, 0.0147, 0.0070], grad_fn=<SqueezeBackward1>)

In [61]:
sent_em=torch.Tensor([])
for s,w in zip(x,att_w):
    w=w.view(1,-1)
    s=torch.squeeze(s,dim=0)
    sent_e=torch.matmul(w,s)
    sent_em=torch.cat((sent_em,sent_e),dim=0)

RuntimeError: size mismatch, got 1, 1x1,3

In [63]:
gru=nn.GRU(input_size=input_dim,hidden_size=2,bidirectional=True)


In [66]:
gru(x[0])

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [90]:
emb=nn.Embedding(num_embeddings =1,embedding_dim=input_dim)

In [108]:

my_dict=[torch.Tensor(v) for k,v in wdv.items()]

In [109]:
my_dict[0]

tensor([ 0.0696,  1.5705, -1.0371, -1.7758,  0.6169, -2.1731, -1.1762,  3.5082,
         4.0245,  1.0452,  0.1777, -0.8022, -0.5311,  4.1145,  1.9032, -2.9305,
         0.5490, -2.4362,  0.3503,  1.2581, -1.7697, -0.2456, -1.9041,  3.7110,
         2.1213,  0.3331, -1.0566,  1.8388, -0.9516,  0.5425,  3.0840, -0.4972,
        -1.7088,  1.2916, -4.3547, -0.3601,  1.8823, -1.0470, -1.5548, -1.7009,
         3.7583,  0.4760,  1.8543,  0.1802, -1.4188, -1.2846,  4.9666,  0.0538,
        -0.9291, -5.1471, -0.4209, -0.9943, -1.9112,  0.8155, -0.6347,  0.5952,
         0.8306,  2.1269, -0.3240,  0.7065,  2.8146, -0.3707, -0.3281,  0.6793,
         2.4985, -0.7090,  2.2290,  1.4793,  2.1250,  0.2532, -0.2294,  1.9990,
         1.6981,  0.4208, -0.1206,  1.1749, -1.8316, -0.9280,  3.0375,  1.5805,
        -1.9440,  0.3508, -2.0383,  0.0799, -2.9112,  1.3426, -1.6303,  2.0359,
         5.4185, -2.0565, -0.4034,  2.6499,  4.0693, -2.4294,  0.7357,  3.8377,
        -3.6958, -1.7261,  0.6617, -1.51

TypeError: 'dict_values' object is not subscriptable

In [105]:
emb(my_dict)

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not list

In [ ]:
emb=nn.Embedding(num_embeddings =len(my_dict),embedding_dim=input_dim)

In [3]:
import pandas as pd
import csv

In [2]:
p=r"D:\Thesis\rerun\wor2vec\fold_0\word2vec_200.model"

In [4]:
dict = pd.read_csv(filepath_or_buffer=p, header=None, sep=" ", quoting=csv.QUOTE_NONE).values[:, 1:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

In [47]:
gru=nn.GRU(input_size=200,hidden_size=3,bidirectional=True)

In [48]:
gru(x)

(tensor([[[ 1.6118e-01, -3.0997e-02,  8.4912e-03, -2.6226e-06,  6.4699e-01,
            0.0000e+00]]], grad_fn=<CatBackward0>),
 tensor([[[ 1.6118e-01, -3.0997e-02,  8.4912e-03]],
 
         [[-2.6226e-06,  6.4699e-01,  0.0000e+00]]], grad_fn=<StackBackward0>))

In [45]:
x=torch.Tensor(wdv['delhi']).reshape(1,1,len(wdv['delhi']))

In [35]:
y=-1*torch.rand(1,1,3 ) + 0

In [46]:
gru(x)

RuntimeError: input.size(-1) must be equal to input_size. Expected 3, got 200

In [44]:
x.shape

torch.Size([200])

In [49]:
x=torch.rand(1,3)
y=torch.rand(1,3)


In [55]:
z=torch.stack([x,y])

tensor([[0.0333, 0.5683, 0.9217]])

In [75]:
x=torch.Tensor(wdv['delhi']).reshape(1,1,len(wdv['delhi']))
y=torch.Tensor(wdv['high']).reshape(1,1,len(wdv['high']))
out=torch.cat((x,y),dim=0)

In [76]:
out.shape

torch.Size([2, 1, 200])

In [1]:
import torch 
import torch.nn as nn
import json
import torch.nn.functional as F

In [54]:
class WordEncoder(nn.Module):
    def __init__(self,args) -> None:
        super(WordEncoder,self).__init__()
        self.input_size = args.input_dim
        self.hidden_dim = args.hidden_dim
        self.gru_layer=nn.GRU(input_size=self.input_size,
                              hidden_size=self.hidden_dim,
                              bidirectional=True)

    def forward(self,inp):
        output = self.gru_layer(inp)
        return output

In [58]:
class argParser():
    def __init__(self,path):
        self.args=self.__arg_parser(path)
        self.input_dim=self.args['INPUT_SIZE']
        self.hidden_dim=self.args['HIDDEN_SIZE']

    def __arg_parser(self,path):
        with open(path,'r') as f:
            args=json.load(f)
        return args

In [60]:
my_arg=argParser(r'D:\Thesis\Final_Presentation\han\args.json')

In [77]:
wd = WordEncoder(my_arg)
ip=wd.forward(out)

In [69]:
x.shape

torch.Size([1, 1, 200])

In [82]:
len(ip)

2

In [2]:
torch.randn(5,3,10)

tensor([[[-1.2805e+00, -1.8922e+00, -3.9934e-01, -2.4294e+00, -7.4389e-01,
          -9.1161e-01, -8.1602e-01, -8.3729e-01, -1.0362e+00, -1.0965e-01],
         [-4.0063e-01, -2.1795e-01, -2.3573e-01,  1.6610e+00, -4.6581e-01,
          -1.5485e+00,  1.6522e-01,  5.3731e-01,  6.2826e-01,  8.6019e-01],
         [ 1.7553e+00, -1.4370e+00, -2.4996e-01,  6.3378e-01, -4.5832e-02,
           4.5836e-01, -1.6988e+00,  8.9590e-01, -2.3443e-01, -4.7332e-01]],

        [[-1.9301e-01,  1.3873e+00,  9.5708e-01, -5.2277e-02, -9.5447e-01,
           7.0795e-01, -6.2272e-01, -9.7577e-01,  5.3204e-01,  1.4106e+00],
         [-7.6347e-01, -2.1477e-01, -1.6375e+00,  8.2077e-01,  8.6696e-01,
           1.3776e+00, -3.8738e-01,  4.0789e-01, -1.0872e+00,  6.5991e-01],
         [-9.9332e-02,  4.4825e-01,  2.7667e-01, -1.6359e+00,  4.6708e-01,
           1.3459e+00, -7.6880e-02,  1.5936e+00,  1.4007e+00,  4.8770e-01]],

        [[ 4.2152e-01, -1.3654e+00, -1.4335e-01,  2.7557e-03,  1.8210e-02,
           3.51

In [8]:
import nltk
from nltk.tokenize import word_tokenize

In [2]:
path=r"D:\Thesis\rerun\wor2vec\fold_0\vocab_200.json"
with open(path,'r') as f:
    wdv=json.load(f)

In [4]:
with open(r'D:\Thesis\Legal_AI\script\legal.1.1\facts\1440.txt', 'r',encoding="utf8") as f:
    context=nltk.tokenize.sent_tokenize(f.read())

In [10]:
vec=word_tokenize(context[0])

In [27]:
sen=torch.Tensor([])
for v in vec:
    try:
        torch.cat((sen,torch.Tensor(wdv[v].lower())),out=sen)
    except:
        torch.cat((sen,torch.zeros(200)),dim=0,out=sen)

RuntimeError: 0unsupported operation: the input tensors cannot refer to any of the output memory locations. Found overlap in input tensor 0

In [35]:
sen=torch.empty(200)
sen=torch.stack([sen,torch.Tensor(wdv['delhi'])],dim=0)



tensor([ 0.0696,  1.5705, -1.0371, -1.7758,  0.6169, -2.1731, -1.1762,  3.5082,
         4.0245,  1.0452,  0.1777, -0.8022, -0.5311,  4.1145,  1.9032, -2.9305,
         0.5490, -2.4362,  0.3503,  1.2581, -1.7697, -0.2456, -1.9041,  3.7110,
         2.1213,  0.3331, -1.0566,  1.8388, -0.9516,  0.5425,  3.0840, -0.4972,
        -1.7088,  1.2916, -4.3547, -0.3601,  1.8823, -1.0470, -1.5548, -1.7009,
         3.7583,  0.4760,  1.8543,  0.1802, -1.4188, -1.2846,  4.9666,  0.0538,
        -0.9291, -5.1471, -0.4209, -0.9943, -1.9112,  0.8155, -0.6347,  0.5952,
         0.8306,  2.1269, -0.3240,  0.7065,  2.8146, -0.3707, -0.3281,  0.6793,
         2.4985, -0.7090,  2.2290,  1.4793,  2.1250,  0.2532, -0.2294,  1.9990,
         1.6981,  0.4208, -0.1206,  1.1749, -1.8316, -0.9280,  3.0375,  1.5805,
        -1.9440,  0.3508, -2.0383,  0.0799, -2.9112,  1.3426, -1.6303,  2.0359,
         5.4185, -2.0565, -0.4034,  2.6499,  4.0693, -2.4294,  0.7357,  3.8377,
        -3.6958, -1.7261,  0.6617, -1.51

In [15]:
rnn = nn.GRU(10, 20, 2)
inpu = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(inpu, h0)

In [16]:
output.shape

torch.Size([5, 3, 20])

In [18]:
inpu

tensor([[[ 1.1582,  0.6373, -0.4620, -1.9412, -0.0884,  0.5555, -1.4863,
          -2.7538,  0.4418, -1.2150],
         [ 1.4238,  0.1332, -0.1600,  0.2254, -0.6721, -0.8195, -1.8595,
          -0.3239, -0.3056, -0.5261],
         [-0.3668,  0.1759,  1.1484,  0.7886, -1.0071, -1.9894,  1.8648,
           0.2261,  0.3849,  2.3369]],

        [[ 1.1326,  0.5817,  0.4349,  0.0872,  0.6344,  0.2148, -0.2052,
           0.2996, -0.1444, -0.6517],
         [ 1.0568,  0.1634,  1.1131,  0.6351, -1.3747,  0.0624, -1.3077,
          -0.1971,  0.2223,  1.3656],
         [ 1.7791, -0.0095, -0.5123,  1.2232,  2.0284,  1.1009,  0.3887,
          -2.3344, -0.1136, -0.1483]],

        [[-0.2504, -0.6894,  0.7301, -1.6632,  0.0198, -1.4827, -1.4362,
          -0.2488,  0.6488, -0.0826],
         [-0.3480,  1.0506, -0.7724,  1.4312, -1.2519,  0.3807, -0.6795,
           0.0465, -0.3087,  1.3418],
         [ 0.6106, -0.7371, -0.3779,  1.4991, -0.4810, -0.7521,  0.5732,
          -1.0979,  1.2449,  0.9038

In [5]:
x=rnn(inpu, h0)

In [6]:
type(x)

tuple

In [8]:
path=r"D:\Thesis\rerun\wor2vec\fold_0\vocab_200.json"
with open(path,'r') as f:
    wdv=json.load(f)

In [12]:
x=torch.Tensor(wdv['delhi']).reshape(1,1,len(wdv['delhi']))
y=torch.Tensor(wdv['high']).reshape(1,1,len(wdv['high']))
out=torch.stack((x,y),dim=0)

In [13]:
out.shape

torch.Size([2, 1, 1, 200])

In [84]:
import json
import os
import shutil

In [51]:
with open(r"D:\Thesis\Legal_AI\script\legal.1.1\IPC_data\ipc_case_offences.json",'r') as f:
    target=json.load(f)

In [52]:
len(target)

6012

In [3]:
output='sen'
if not os.path.isdir(output):
    os.mkdir(output)
for k,v in target.items():
    shutil.copy(os.path.join(r'D:\Thesis\Legal_AI\script\legal.1.1\sentences', f"{k}.txt"),output)
    

In [12]:
with open(r'D:\Thesis\Legal_AI\script\legal.1.1\facts\1440.txt','r') as f:
    content= f.read()

In [13]:
words = content.split()
words = list(filter(lambda x: x != "", words))
length = len(words)
words = [word.strip("./-?!") for word in words]

In [15]:
sent_emb=[]
for w in words:
    sent_emb.append(wdv.get(w,torch.zeros(200)))

In [31]:
sent_emb[0]

200

In [16]:
sent_emb=torch.stack(sent_emb)

TypeError: expected Tensor as element 8 in argument 0, but got list

In [38]:
x=wdv.get('Delhi',torch.zeros(200))

In [40]:
x.shape

torch.Size([200])

In [24]:
se=[torch.zeros(10) for i in range(10)]

In [44]:
se=[]
for i in range(10):
    se.append(torch.zeros(200))

In [43]:
type(se[0])

torch.Tensor

In [45]:
torch.stack(se,dim=0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [46]:
import torch

In [48]:
x=torch.load(r'D:\Thesis\Legal_AI\script\legal.1.1\save\28102.pt')

In [49]:
x.shape

torch.Size([200])

In [53]:
import json 
import os

In [54]:
save_p=r'D:\Thesis\Legal_AI\script\legal.1.1\save'
test_p=r'D:\Thesis\Legal_AI\script\legal.1.1\IPC_data\fold_0\test'
train_p=r'D:\Thesis\Legal_AI\script\legal.1.1\IPC_data\fold_0\train'

In [87]:
test_list=os.listdir(test_p)
test_list=[k.split('.')[0] for k in test_list]
train_list=os.listdir(train_p)
train_list=[k.split('.')[0] for k in train_list]
original_list=os.listdir(save_p)
original_list.remove("gen_embeds.log")
original_list=[k.split('.')[0] for k in original_list]


In [82]:
x=[k for k in train_list if k in original_list]


In [83]:
len(x)

3901

In [95]:
output='Han_vect'

if not os.path.isdir(output):
    os.mkdir(output)

if not os.path.isdir(os.path.join(output,'test')):
    os.mkdir(os.path.join(output,'test'))

if not os.path.isdir(os.path.join(output,'train')):
    os.mkdir(os.path.join(output,'train'))


In [96]:
for k in test_list:
    shutil.copy(os.path.join(r'D:\Thesis\Legal_AI\script\legal.1.1\save', f"{k}.pt"),os.path.join(output,'test'))

for k in train_list:
    shutil.copy(os.path.join(r'D:\Thesis\Legal_AI\script\legal.1.1\save', f"{k}.pt"),os.path.join(output,'train'))